ecommerce:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres  # Must match service name
      user: steev
      password: Sugukumar@0101
      port: 5432
      dbname: mydb
      schema: public  # Explicit schema
      threads: 1